[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["fuzz"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
license = "MIT"

[workspace.dependencies]
cecli = { path = "crates/cecli" }
bitflags = "2"
rsa = "0.9"
sha2 = "0.10"
criterion = "0.5"
cecli-core = { path = "crates/cecli-core" }
cecli-pe = { path = "crates/cecli-pe" }
cecli-metadata = { path = "crates/cecli-metadata" }
cecli-cil = { path = "crates/cecli-cil" }
cecli-pdb = { path = "crates/cecli-pdb" }
cecli-mdb = { path = "crates/cecli-mdb" }
cecli-rocks = { path = "crates/cecli-rocks" }

[profile.release]
debug = true
