//! The CIL instruction identifier enumeration (`Mono.Cecil.Cil.Code`).
//!
//! Variant discriminants follow the declaration order of the C# `Code`
//! enum; they are *not* the byte encodings (see [`crate::opcode::OpCode`]
//! for the wire encoding of each instruction).

/// Every CIL instruction identifier defined by ECMA-335 partition III.
///
/// Variant names intentionally keep the exact `Mono.Cecil.Cil.Code` spelling
/// (e.g. `Ldarg_0`, `Ldc_I4_M1`), hence the style allowance below.
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[repr(u16)]
pub enum Code {
    Nop,
    Break,
    Ldarg_0,
    Ldarg_1,
    Ldarg_2,
    Ldarg_3,
    Ldloc_0,
    Ldloc_1,
    Ldloc_2,
    Ldloc_3,
    Stloc_0,
    Stloc_1,
    Stloc_2,
    Stloc_3,
    Ldarg_S,
    Ldarga_S,
    Starg_S,
    Ldloc_S,
    Ldloca_S,
    Stloc_S,
    Ldnull,
    Ldc_I4_M1,
    Ldc_I4_0,
    Ldc_I4_1,
    Ldc_I4_2,
    Ldc_I4_3,
    Ldc_I4_4,
    Ldc_I4_5,
    Ldc_I4_6,
    Ldc_I4_7,
    Ldc_I4_8,
    Ldc_I4_S,
    Ldc_I4,
    Ldc_I8,
    Ldc_R4,
    Ldc_R8,
    Dup,
    Pop,
    Jmp,
    Call,
    Calli,
    Ret,
    Br_S,
    Brfalse_S,
    Brtrue_S,
    Beq_S,
    Bge_S,
    Bgt_S,
    Ble_S,
    Blt_S,
    Bne_Un_S,
    Bge_Un_S,
    Bgt_Un_S,
    Ble_Un_S,
    Blt_Un_S,
    Br,
    Brfalse,
    Brtrue,
    Beq,
    Bge,
    Bgt,
    Ble,
    Blt,
    Bne_Un,
    Bge_Un,
    Bgt_Un,
    Ble_Un,
    Blt_Un,
    Switch,
    Ldind_I1,
    Ldind_U1,
    Ldind_I2,
    Ldind_U2,
    Ldind_I4,
    Ldind_U4,
    Ldind_I8,
    Ldind_I,
    Ldind_R4,
    Ldind_R8,
    Ldind_Ref,
    Stind_Ref,
    Stind_I1,
    Stind_I2,
    Stind_I4,
    Stind_I8,
    Stind_R4,
    Stind_R8,
    Add,
    Sub,
    Mul,
    Div,
    Div_Un,
    Rem,
    Rem_Un,
    And,
    Or,
    Xor,
    Shl,
    Shr,
    Shr_Un,
    Neg,
    Not,
    Conv_I1,
    Conv_I2,
    Conv_I4,
    Conv_I8,
    Conv_R4,
    Conv_R8,
    Conv_U4,
    Conv_U8,
    Callvirt,
    Cpobj,
    Ldobj,
    Ldstr,
    Newobj,
    Castclass,
    Isinst,
    Conv_R_Un,
    Unbox,
    Throw,
    Ldfld,
    Ldflda,
    Stfld,
    Ldsfld,
    Ldsflda,
    Stsfld,
    Stobj,
    Conv_Ovf_I1_Un,
    Conv_Ovf_I2_Un,
    Conv_Ovf_I4_Un,
    Conv_Ovf_I8_Un,
    Conv_Ovf_U1_Un,
    Conv_Ovf_U2_Un,
    Conv_Ovf_U4_Un,
    Conv_Ovf_U8_Un,
    Conv_Ovf_I_Un,
    Conv_Ovf_U_Un,
    Box,
    Newarr,
    Ldlen,
    Ldelema,
    Ldelem_I1,
    Ldelem_U1,
    Ldelem_I2,
    Ldelem_U2,
    Ldelem_I4,
    Ldelem_U4,
    Ldelem_I8,
    Ldelem_I,
    Ldelem_R4,
    Ldelem_R8,
    Ldelem_Ref,
    Stelem_I,
    Stelem_I1,
    Stelem_I2,
    Stelem_I4,
    Stelem_I8,
    Stelem_R4,
    Stelem_R8,
    Stelem_Ref,
    Ldelem_Any,
    Stelem_Any,
    Unbox_Any,
    Conv_Ovf_I1,
    Conv_Ovf_U1,
    Conv_Ovf_I2,
    Conv_Ovf_U2,
    Conv_Ovf_I4,
    Conv_Ovf_U4,
    Conv_Ovf_I8,
    Conv_Ovf_U8,
    Refanyval,
    Ckfinite,
    Mkrefany,
    Ldtoken,
    Conv_U2,
    Conv_U1,
    Conv_I,
    Conv_Ovf_I,
    Conv_Ovf_U,
    Add_Ovf,
    Add_Ovf_Un,
    Mul_Ovf,
    Mul_Ovf_Un,
    Sub_Ovf,
    Sub_Ovf_Un,
    Endfinally,
    Leave,
    Leave_S,
    Stind_I,
    Conv_U,
    Arglist,
    Ceq,
    Cgt,
    Cgt_Un,
    Clt,
    Clt_Un,
    Ldftn,
    Ldvirtftn,
    Ldarg,
    Ldarga,
    Starg,
    Ldloc,
    Ldloca,
    Stloc,
    Localloc,
    Endfilter,
    Unaligned,
    Volatile,
    Tail,
    Initobj,
    Constrained,
    Cpblk,
    Initblk,
    No,
    Rethrow,
    Sizeof,
    Refanytype,
    Readonly,
}

impl Code {
    /// Number of variants in this enumeration (matches the C# `Code` enum).
    pub const COUNT: usize = 219;
}

impl From<Code> for u16 {
    fn from(code: Code) -> u16 {
        code as u16
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn discriminants_are_declaration_order() {
        assert_eq!(Code::Nop as u16, 0);
        assert_eq!(Code::Ret as u16, 41);
        assert_eq!(Code::Conv_U as u16, 190);
        assert_eq!(Code::Readonly as u16, 218);
        assert_eq!(Code::COUNT, 219);
    }
}
